language: go
go:
    - 1.6
    - 1.7
    - tip
go_import_path: github.com/vetinari/go-ldapdn
install:
    - go get gopkg.in/asn1-ber.v1
    - go get gopkg.in/ldap.v2
    - go get code.google.com/p/go.tools/cmd/cover || go get golang.org/x/tools/cmd/cover
    - go get github.com/golang/lint/golint || true
    - go build -v ./...
script:
    - make test
    - make fmt
    - make vet
    - make lint

